# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('short', models.CharField(max_length=255, verbose_name='Skr\xf3t')),
                ('description', models.TextField(verbose_name='Opis')),
                ('added_at', models.DateField(verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Konkurs',
                'verbose_name_plural': 'Konkursy',
            },
        ),
    ]
