# Generated by Django 3.0.3 on 2020-07-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20200715_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Recipe',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='quiz',
        ),
        migrations.AddField(
            model_name='photo',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quizzes.Recipe', verbose_name='Przepis'),
            preserve_default=False,
        ),
    ]
